Modules/Basic/routes/web.php
<?php

declare(strict_types = 1);

use Essprendimai\Basic\Enums\LanguageEnum;
use Essprendimai\Basic\Enums\LanguageRouteNameEnum;
use Essprendimai\Basic\Http\Controllers\Auth\LoginController;
use Essprendimai\Basic\Http\Controllers\Auth\RegisterController;
use Essprendimai\Basic\Http\Middleware\EnsureEmailIsVerified;
use Essprendimai\Basic\Http\Middleware\IsClient;
use Essprendimai\Basic\Http\Middleware\LimitsBackendRouteAccess;
use Illuminate\Auth\Middleware\Authenticate;

// ---------- Everyone ----------
Route::get('/', 'WelcomeController@index')->name('welcome');
Route::post('admin-panel-logout', 'Auth\LoginController@logout')->name('admin-panel.logout');
Route::post(LoginController::CLIENT_LOGOUT_ROUTE_NAME, 'Auth\LoginController@logout')->name('client.logout');

// ---------- Verify email----------
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}', 'Auth\VerificationController@verify')->name('verification.verify');
Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');

// ---------- Reset password ----------
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

// ---------- Guest ----------
Route::group([
    'middleware' => ['web', 'custom-guest'],
], function(){
    Route::get(LoginController::ADMIN_LOGIN_ROUTE_NAME, 'Auth\LoginController@showLoginForm')->name('admin-panel.login-form');
    Route::get(LoginController::ADMIN_LOGIN_ROUTE_NAME, 'Auth\LoginController@showLoginForm')->name('login');
    Route::post(LoginController::ADMIN_LOGIN_ROUTE_NAME, 'Auth\LoginController@login')->name('admin-panel.login');

    Route::get(LoginController::CLIENT_LOGIN_ROUTE_NAME, 'Auth\LoginController@showClientLoginForm')->name('client.login-form');
    Route::post(LoginController::CLIENT_LOGIN_ROUTE_NAME, 'Auth\LoginController@login')->name('client.login');

    Route::get(RegisterController::CLIENT_REGISTER_ROUTE_NAME, 'Auth\RegisterController@showRegistrationForm')->name('client.register-form');
    Route::post(RegisterController::CLIENT_REGISTER_ROUTE_NAME, 'Auth\RegisterController@register')->name('client.register');
});

// ---------- Client ----------
Route::group([
    'middleware' => ['web', IsClient::class, EnsureEmailIsVerified::class],
    'prefix' => 'client',
    'as' => 'client.',
], function(){
    Route::get('home', 'ClientHomeController@index')->name('home');

    Route::get('profile/edit', 'ClientProfileController@edit')->name('profile.edit');
    Route::post('profile/store', 'ClientProfileController@store')->name('profile.store');
});

// ---------- Language ----------
Route::group([
    'middleware' => ['web'],
], function(){
    Route::get('change-language/{language}', 'LanguageController@change')->name('language.change');
    Route::get('change-language-backend/{language}', 'LanguageController@changeBackend')->name('language.change-backend');

    foreach (LanguageEnum::enum() as $language) {
        Route::get(LanguageRouteNameEnum::from($language->id())->name() . '/{pageUrl}', 'PagesController@showPageByPageUrl')
            ->name('page.' . $language->id() . '.page-by-url');

        Route::get(LanguageRouteNameEnum::from($language->id())->name() . '/{categoryUrl}/{pageUrl}', 'PagesController@showPageByCategoryAndPageUrl')
            ->name('page.' . $language->id() . '.page-by-category-url');
    }
});

// ---------- Admin ----------
Route::group([
    'middleware' => ['web', Authenticate::class, LimitsBackendRouteAccess::class],
    'prefix' => 'backend',
], function(){
    Route::get('home', 'HomeController@index')->name('backend.home');

    Route::get('change-password', 'ChangePasswordController@changePassword')->name('backend.change-password.form');
    Route::post('change-password', 'ChangePasswordController@postChangePassword')->name('backend.change-password.post');

    Route::resource('users', 'UserController', [
        'except' => [
            'edit',
        ],
        'names' => [
            'store' => 'backend.users.store',
            'show' => 'backend.users.show',
            'index' => 'backend.users.index',
            'destroy' => 'backend.users.destroy',
            'update' => 'backend.users.update',
            'create' => 'backend.users.create',
        ],
    ]);
    Route::post('users/send-message', 'UserController@sendMessageToUsers')->name('backend.users.send-message-to-users');
    Route::post('users/send-message-from-group', 'UserController@sendMessageToUsersFromGroup')->name('backend.users.send-message-to-users-from-group');
    Route::post('users/add-users-to-group', 'UserController@addUsersToGroup')->name('backend.users.add-users-to-group');
    Route::get('users/delete-user-from-group/{userId}/{groupId}','UserController@removeFromGroup')->name('backend.users.remove-user-from-group');

    Route::resource('role', 'RolesController', ['as' => 'backend']);
    Route::resource('categories', 'CategoriesController', ['as' => 'backend']);
    Route::resource('groups', 'GroupsController', [
        'except' => [
            'show',
        ],
        'as' => 'backend',
    ]);

    Route::resource('pages', 'PagesController', [
        'except' => [
            'show',
        ],
        'as' => 'backend',
    ]);
    Route::get('pages/change-status/{page}/{status}', 'PagesController@changeStatus')->name('backend.pages.change_status');
    Route::get('pages/group', 'PagesController@groupIndex')->name('backend.pages.group.index');

    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('backend.logs');
    Route::get('send-verification/{user}', 'Auth\AdminVerificationController@sendVerification')->name('backend.send-verification');
    Route::get('send-draft-user-verification/{user}', 'Auth\AdminVerificationController@sendDraftUserVerification')->name('backend.send-draft-user-verification');
});

Modules/Basic/Resources/views/pages/create.blade.php
@extends('basic-view::layouts.app-gate')

@push('styles')
    <link href="/css/basic-view/froala.css" rel="stylesheet">
@endpush

@section('content-title')
    <h1>
        <i class="fa fa-plus"></i> {{ __('basic::pages.pages_page.new_title') }}
    </h1>
    <p>{{ __('basic::pages.pages_page.new_title_description') }}</p>
@endsection

@section('content-location')
    <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
    <li class="breadcrumb-item"><a href="{{ route('backend.pages.index') }}">{{ __('basic::pages.menu.pages') }}</a></li>
    <li class="breadcrumb-item"><a href="{{ route('backend.pages.create') }}">{{ __('basic::pages.menu.new') }}</a></li>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                {!! BootForm::open(['route' => 'backend.pages.store', 'enctype' => 'multipart/form-data', 'files' => true]) !!}
                {!! BootForm::text('key', __('basic::pages.pages_page.key'), null, ['required']) !!}

                <hr/>

                @foreach (\Essprendimai\Basic\Services\LanguageService::getAllActiveLanguages() as $language)
                    <div>
                        <img class="app-menu__icon" style="height: 20px;margin-left: -5px;" src="/images/languages/{{ $language }}.png"/> &nbsp;&nbsp;
                        {{ __($language->name()) }}
                        <br/>
                        <br/>
                    </div>

                    {!! BootForm::text('title[' . $language->id() . ']', __('basic::pages.pages_page.page_title'), null) !!}
                    {!! BootForm::text('url[' . $language->id() . ']', __('basic::pages.pages_page.page_url'), null) !!}

                    <div class="animated-checkbox">
                        <label>
                            <input type="checkbox" name="external_url[{{ $language->id() }}]">
                            <span class="label-text">{{ __('basic::pages.pages_page.external_url') }}</span>
                        </label>
                    </div>

                    <div class="animated-checkbox">
                        <label>
                            <input type="checkbox" name="is_template[{{ $language->id() }}]">
                            <span class="label-text">{{ __('basic::pages.pages_page.is_template') }}</span>
                        </label>
                    </div>

                    {!! BootForm::file('featured_image[' . $language->id() . ']', __('basic::pages.pages_page.featured_image'), ['multiple' => true, 'class' => 'form-control']) !!}

                    <label>{{ __('basic::pages.pages_page.menu_id') }}</label>
                    @foreach ($menuGroups as $menuGroup)
                        <div class="animated-checkbox">
                            <label>
                                <input type="checkbox" name="menu[{{ $language->id() }}][]" value="{{ $menuGroup->id }}">
                                <span class="label-text">{{ $menuGroup->title }}</span>
                            </label>
                        </div>
                    @endforeach

                    {!! BootForm::select('category[' . $language->id() . ']', __('basic::pages.pages_page.category_id'), $categoryByLanguages[$language->id()] ?? [0 => '-']) !!}

                    <br/>

                    {!! BootForm::textarea('text[' . $language->id() . ']', __('basic::pages.pages_page.page_text'), null) !!}

                    <div class="toggle">
                        <label>
                            <input type="checkbox" name="active[{{ $language->id() }}]" value="0"><span class="button-indecator">{{  __('basic::pages.pages_page.active') }}</span>
                        </label>
                    </div>

                    <hr/>
                @endforeach

                {!! BootForm::submit(__('basic::pages.pages_page.create')) !!}
                {!! BootForm::close() !!}
            </div>
        </div>
    </div>
@endsection

@push('pre.scripts')
    <script src="/js/basic-view/froala.js"></script>
@endpush

@push('scripts')
    <script>
        $(function() {
            $('textarea').froalaEditor()
        });
    </script>
@endpush

Modules/Basic/Resources/views/pages/edit.blade.php
@extends('basic-view::layouts.app-gate')

@push('styles')
    <link href="/css/basic-view/froala.css" rel="stylesheet">
@endpush

@section('content-title')
    <h1>
        <i class="fa fa-edit"></i> {{ __('basic::pages.pages_page.edit_title') }}
    </h1>
    <p>{{ __('basic::pages.pages_page.edit_title', ['attribute' => $key]) }}</p>
@endsection

@section('content-location')
    <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
    <li class="breadcrumb-item"><a href="{{ route('backend.pages.index') }}">{{ __('basic::pages.menu.pages') }}</a></li>
    <li class="breadcrumb-item"><a href="{{ route('backend.pages.edit', $key)  }}">{{ $key }}</a></li>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                {!! BootForm::open(['route' => ['backend.pages.update', $key], 'enctype' => 'multipart/form-data', 'files' => true]) !!}
                {{ method_field('PUT') }}
                {!! BootForm::text('key', __('basic::pages.pages_page.key'), $key, ['disabled']) !!}
                {!! BootForm::hidden('key', $key) !!}

                <hr/>

                @foreach ($filteredPages as $language => $page)
                    <div>
                        <img class="app-menu__icon" style="height: 20px;margin-left: -5px;" src="/images/languages/{{ $language }}.png"/> &nbsp;&nbsp;
                        {{ __(\Essprendimai\Basic\Enums\LanguageEnum::from($language)->name()) }}
                        <br/>
                        <br/>
                    </div>

                    {{ BootForm::text(
                        'title[' . $language . ']',
                        __('basic::pages.pages_page.page_title'),
                        $page ? $page->title : null
                    ) }}

                    {!! BootForm::hidden('old_url[' . $language  . ']', $page ? $page->url : null) !!}
                    {{ BootForm::text(
                        'url[' . $language  . ']',
                        __('basic::pages.pages_page.page_url'),
                        $page ? $page->url : null
                    ) }}

                    <div class="animated-checkbox">
                        <label>
                            <input type="checkbox" name="external_url[{{ $language }}]" {{ $page && $page->external_url ? 'checked' : '' }}>
                            <span class="label-text">{{ __('basic::pages.pages_page.external_url') }}</span>
                        </label>
                    </div>

                    <div class="animated-checkbox">
                        <label>
                            <input type="checkbox" name="is_template[{{ $language }}]" {{ $page && $page->is_template ? 'checked' : '' }}>
                            <span class="label-text">{{ __('basic::pages.pages_page.is_template') }}</span>
                        </label>
                    </div>

                    @if ($page && $page->featured_image)
                        <div class="row">
                            <div class="col-1">
                                <img width="100%" src="{{ $page->featured_image }}"/>
                            </div>
                            <div class="col-11">
                                {!! BootForm::file('featured_image[' . $language . ']', __('basic::pages.pages_page.featured_image'), ['multiple' => true, 'class' => 'form-control']) !!}
                            </div>
                        </div>
                    @else
                        {!! BootForm::file('featured_image[' . $language . ']', __('basic::pages.pages_page.featured_image'), ['multiple' => true, 'class' => 'form-control']) !!}
                    @endif

                    <label>{{ __('basic::pages.pages_page.menu_id') }}</label>
                    @foreach ($menuGroups as $menuGroup)
                        <div class="animated-checkbox">
                            <label>
                                <input type="checkbox" name="menu[{{ $language }}][]" value="{{ $menuGroup->id }}" {{ $page && $page->menuGroups->where('key', $menuGroup->key)->isNotEmpty() ? 'checked' : ''}}>
                                <span class="label-text">{{ $menuGroup->title }}</span>
                            </label>
                        </div>
                    @endforeach

                    {!! BootForm::select(
                        'category[' . $language . ']',
                         __('basic::pages.pages_page.category_id'),
                         $categoryByLanguages[$language] ?? [0 => '-'],
                         $page && $page->category_id ? $page->category_id : 0
                    ) !!}

                    {!! BootForm::textarea(
                        'text[' . $language . ']',
                        __('basic::pages.pages_page.page_text'),
                         $page->text ?? ''
                     ) !!}

                    <div class="toggle">
                        <label>
                            <input type="checkbox" name="active[{{ $language }}]" {{ $page && $page->active ? 'checked' : ''}}><span class="button-indecator">{{  __('basic::pages.pages_page.active') }}</span>
                        </label>
                    </div>

                    <div class="input-group mb-3">
                        <input
                            name="read_link"
                            type="text"
                            class="form-control clipboard-data"
                            aria-label="Read link"
                            aria-describedby="read-link-addon"
                            disabled=""
                            value="{{ get_page_link($page) }}"
                        >
                        <div class="input-group-append">
                        <span class="input-group-text" id="read-link-addon">
                            <i class="clipboard fa fa-clipboard" style="cursor:pointer;"></i>
                        </span>
                        </div>
                    </div>

                    <hr/>
                @endforeach

                {!! BootForm::submit(__('basic::pages.pages_page.edit')) !!}
                {!! BootForm::close() !!}
            </div>
        </div>
    </div>
@endsection

@push('pre.scripts')
    <script src="/js/basic-view/froala.js"></script>
    <script src="/js/basic-view/clipboard.js"></script>
@endpush

@push('scripts')
    <script>
        $(function() {
            $('textarea').froalaEditor();

            $('.clipboard').on('click', function(event){
                var copyText = event.target || event.srcElement;
                copyText = $(copyText).closest('.input-group').find('input')[0];

                copyText.disabled = false;
                copyText.select();
                copyText.disabled = true;
                document.execCommand("Copy");
            });
        });
    </script>
@endpush

Modules/Basic/Resources/views/pages/index.blade.php
@extends('basic-view::layouts.app-gate')

@section('content-title')
    <h1>
        <i class="fa fa-file"></i> {{ __('basic::pages.pages_page.title') }} &nbsp;&nbsp;&nbsp;  <a class="btn btn-primary" href="{{ route('backend.pages.create') }}"><i class="fa fa-plus"></i> {{ __('basic::pages.pages_page.create') }}</a>
    </h1>
    <p>{{ __('basic::pages.pages_page.title_description') }}</p>
@endsection

@section('content-location')
    <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
    <li class="breadcrumb-item"><a href="{{ route('backend.pages.index') }}">{{ __('basic::pages.menu.pages') }}</a></li>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                @if (isset($pages))
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>{{ __('basic::pages.pages_page.key') }}</th>
                            <th>{{ __('basic::pages.pages_page.actions') }}</th>
                            <th>{{ __('basic::pages.pages_page.actions') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($pages as $page)
                            <tr>
                                <td width="25%">
                                    @if ($page->featured_image)
                                        <img height="100px" src="{{ $page->featured_image }}"/>
                                        <br/>
                                    @endif

                                    {{ $page->key }}
                                    {!!
                                        $page->active ?
                                            '<span class="badge badge-primary">' . __("basic::pages.active") . '</span>' :
                                            '<span class="badge badge-warning">' . __("basic::pages.inactive") . '</span>'
                                    !!}
                                    {!! $page->is_template ? '<span class="badge badge-warning">' . __("basic::pages.template") . '</span>' : '' !!}
                                </td>
                                <td width="50%">
                                    <div class="input-group mb-3">
                                        <input
                                            name="read_link"
                                            type="text"
                                            class="form-control clipboard-data"
                                            aria-label="Read link"
                                            aria-describedby="read-link-addon"
                                            disabled=""
                                            value="{{ get_page_link($page) }}"
                                        >
                                        <div class="input-group-append">
                                            <span class="input-group-text" id="read-link-addon">
                                                <i class="clipboard fa fa-clipboard" style="cursor:pointer;"></i>
                                            </span>
                                        </div>
                                    </div>
                                </td>
                                <td width="25%">
                                    <a href="{{ route('backend.pages.edit', $page->key) }}" class="btn btn-sm btn-info">
                                        <i class="fas fa-edit"></i> {{ __('basic::pages.pages_page.edit') }}
                                    </a>

                                    @if ($page->active)
                                        <a class="btn btn-sm btn-warning" href="{{ route('backend.pages.change_status', [$page->id, 0]) }}">
                                            <i class="fa fa-toggle-off"></i> {{ __('basic::pages.disable') }}
                                        </a>
                                    @else
                                        <a class="btn btn-sm btn-primary" href="{{ route('backend.pages.change_status', [$page->id, 1]) }}">
                                            <i class="fa fa-toggle-on"></i> {{ __('basic::pages.activate') }}
                                        </a>
                                    @endif

                                    {!! BootForm::inline(['route' => ['backend.pages.destroy', $page->key], 'method' => 'DELETE', 'style' => 'display:inline']) !!}
                                    {!! Form::button(
                                     '<i class="fa fa-trash"></i> ' . __('basic::pages.pages_page.delete'),
                                     [
                                         'type' => 'submit',
                                         'class' => 'btn-danger btn btn-sm',
                                         'title' => __('basic::pages.pages_page.delete'),
                                         'onclick'=> 'return confirm("' . __('basic::pages.pages_page.confirm_delete') . '")'
                                     ]) !!}
                                    {!! BootForm::close() !!}
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="4">{{ __('basic::pages.pages_page.empty_list') }}</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>

                    {{ $pages->render() }}
                @endif
            </div>
        </div>
    </div>
@endsection

@push('pre.scripts')
    <script src="/js/basic-view/clipboard.js"></script>
@endpush

@push('scripts')
    <script>
        $(function() {
            $('.clipboard').on('click', function(event){
                var copyText = event.target || event.srcElement;
                copyText = $(copyText).closest('.input-group').find('input')[0];

                copyText.disabled = false;
                copyText.select();
                copyText.disabled = true;
                document.execCommand("Copy");
            });
        });
    </script>
@endpush

Modules/Basic/Resources/views/pages/menu-index.blade.php
@extends('basic-view::layouts.app-gate')

@section('content-title')
    <h1>
        <i class="fa fa-file"></i> {{ __('basic::pages.pages_page.title') }} &nbsp;&nbsp;&nbsp;  <a class="btn btn-primary" href="{{ route('backend.pages.create') }}"><i class="fa fa-plus"></i> {{ __('basic::pages.pages_page.create') }}</a>
    </h1>
    <p>{{ __('basic::pages.pages_page.title_description') }}</p>
@endsection

@section('content-location')
    <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
    <li class="breadcrumb-item"><a href="{{ route('backend.pages.index') }}">{{ __('basic::pages.menu.pages') }}</a></li>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                @if (isset($pages))
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>{{ __('basic::pages.pages_page.key') }}</th>
                            <th>{{ __('basic::pages.pages_page.actions') }}</th>
                            <th>{{ __('basic::pages.pages_page.actions') }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @forelse($pages as $page)
                            <tr>
                                <td width="25%">{{ $page->key }} {!! $page->active ? '<span class="badge badge-primary">' . __("basic::pages.active") . '</span>' : '<span class="badge badge-warning">' . __("basic::pages.inactive") . '</span>' !!}</td>
                                <td width="50%">
                                    <div class="input-group mb-3">
                                        <input
                                            name="read_link"
                                            type="text"
                                            class="form-control clipboard-data"
                                            aria-label="Read link"
                                            aria-describedby="read-link-addon"
                                            disabled=""
                                            value="{{ get_page_link($page) }}"
                                        >
                                        <div class="input-group-append">
                                            <span class="input-group-text" id="read-link-addon">
                                                <i class="clipboard fa fa-clipboard" style="cursor:pointer;"></i>
                                            </span>
                                        </div>
                                    </div>
                                </td>
                                <td width="25%">
                                    <a href="{{ route('backend.pages.edit', $page->key) }}" class="btn btn-sm btn-info">
                                        <i class="fas fa-edit"></i> {{ __('basic::pages.pages_page.edit') }}
                                    </a>

                                    @if ($page->active)
                                        <a class="btn btn-sm btn-warning" href="{{ route('backend.pages.change_status', [$page->id, 0]) }}">
                                            <i class="fa fa-toggle-off"></i> {{ __('basic::pages.disable') }}
                                        </a>
                                    @else
                                        <a class="btn btn-sm btn-primary" href="{{ route('backend.pages.change_status', [$page->id, 1]) }}">
                                            <i class="fa fa-toggle-on"></i> {{ __('basic::pages.activate') }}
                                        </a>
                                    @endif

                                    {!! BootForm::inline(['route' => ['backend.pages.destroy', $page->key], 'method' => 'DELETE', 'style' => 'display:inline']) !!}
                                    {!! Form::button(
                                     '<i class="fa fa-trash"></i> ' . __('basic::pages.pages_page.delete'),
                                     [
                                         'type' => 'submit',
                                         'class' => 'btn-danger btn btn-sm',
                                         'title' => __('basic::pages.pages_page.delete'),
                                         'onclick'=> 'return confirm("' . __('basic::pages.pages_page.confirm_delete') . '")'
                                     ]) !!}
                                    {!! BootForm::close() !!}
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="2">{{ __('basic::pages.pages_page.empty_list') }}</td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>

                    {{ $pages->render() }}
                @endif
            </div>
        </div>
    </div>
@endsection

@push('pre.scripts')
    <script src="/js/basic-view/clipboard.js"></script>
@endpush

@push('scripts')
    <script>
        $(function() {
            $('.clipboard').on('click', function(event){
                var copyText = event.target || event.srcElement;
                copyText = $(copyText).closest('.input-group').find('input')[0];

                copyText.disabled = false;
                copyText.select();
                copyText.disabled = true;
                document.execCommand("Copy");
            });
        });
    </script>
@endpush